feat: added project structure
rawen554/go-loyal pull request #1
Opened 2023-07-07 06:12 UTC by rawen554

2023-07-30 20:28 UTC, s-shpak requested changes

2023-07-30 20:28 UTC, s-shpak commented on go.mod
Надо обновить с помощью `go mod tidy`

2023-07-30 20:28 UTC, s-shpak commented on Makefile
> +clean-run: build run
Зависимости таргета не обязательно будут выполняться в приведенной последовательности. Чтобы добавить такой таргет корректно, надо из него вызвать таргет, запускающий приложение, который, в свою очередь, будет зависеть от `build`. Таргеты, кстати, можно делать невызываемыми напрямую, что может помочь здесь

2023-07-30 20:28 UTC, s-shpak commented on .golangci-lint.yml
Линтер репортит проблемы

2023-07-30 20:28 UTC, s-shpak commented on docker-compose.yml
> +  gophermart-db:
Это необязательно делать: в реальных проектах сервисы, которые не должны быть напрямую доступны пользователю, не экспозят, а помещают во внутреннюю сеть докер-компоуза, так, чтобы только у других сервисов был к ним доступ.

Этот коммент можно зарезолвить

2023-07-30 20:28 UTC, s-shpak commented on db/init/0001_init.sql
> +CREATE TYPE order_status AS ENUM (
Это стоит перенести в миграцию. Также тип создается для конкретной БД, потому необходимо создать его в `gophermart`

2023-07-30 20:28 UTC, s-shpak commented on cmd/gophermart/main.go
> +	r := app.SetupRouter()
Логику инициализации сервера я бы вынес в пакет `app`

2023-07-30 20:28 UTC, s-shpak commented on cmd/gophermart/main.go
> +	storage, err := store.NewPostgresStore(ctx, config.DatabaseURI, logger.LogLevel(config.LogLevel))
Используй один логгер для логгирования всего в твоем приложении. Это не значит, что во все компоненты надо передавать один и тот же объект: просто твой корневой логгер (который ты настроишь в здесь) сможет порождать компонентные логгеры, которые будут вести себя так же как и корневой (например, логгировать в файл вместо стандартного выводы, будут использовать тот же формат и т.д.)

2023-07-30 20:28 UTC, s-shpak commented on cmd/gophermart/main.go
> +	ordersChan := make(chan *models.Order, 10)
Не вижу смысла создавать канал здесь: ты же не читаешь его в этой функции. Желатетльно, чтобы канал создавал тот компонент, который будет в этот канал писать - так проще будет понять, кому его закрыть

2023-07-30 20:28 UTC, s-shpak commented on cmd/gophermart/main.go
> +	}(ctx, componentsErrs)
Тут `componentsErrs` не используется

2023-07-30 20:28 UTC, s-shpak commented on internal/config/config.go
> +	flag.IntVar(&config.LogLevel, "l", config.LogLevel, "0, 1, 2, 3")
Не ясно, что означют эти цифры: необходимо либо добавить информацию об этом, либо позволить пользователю передавать что-то имеющее смысл (info, warn и т.д.), а потом это преобразовывать

2023-07-30 20:28 UTC, s-shpak commented on internal/config/config.go
> +	Seed        string `env:"SEED" envDefault:"b4952c3809196592c026529df00774e46bfb5be0"`
Неудачное имя - лучше назвать это ключом

2023-07-30 20:28 UTC, s-shpak commented on internal/config/config.go
> +	flag.StringVar(&config.Seed, "s", config.Seed, "seed")
Здесь лучше объяснить пользователю назначение этого флага

2023-07-30 20:28 UTC, s-shpak commented on internal/adapters/store/store.go
> +func NewPostgresStore(ctx context.Context, dsn string, logLevel logger.LogLevel) (Store, error) {
Ты и так возвращаешь интерфейся (кстати, зачем?). В этом случае нет смысла указывать с какой СУБД ты работаешь

2023-07-30 20:28 UTC, s-shpak commented on internal/adapters/store/store.go
> +	return &DBStore{conn: conn}, nil
Лучше использовать пул соединений для отправления запросов в БД

2023-07-30 20:28 UTC, s-shpak commented on internal/adapters/store/store.go
> +type Store interface {
не уверен, что объявление этого интерфейса необходимо здесь

2023-07-30 20:28 UTC, s-shpak commented on internal/adapters/store/store.go
> +	for {
Этот коммент можно зарезолвить

В реальности подоные задачи решаются внешними средствами. Например, если ты используешь докер-компоуз, то внутри ты можешь определить зависимость твоего сервиса от БД так, чтобы сервис дожидался старта БД. Но для учебного задания такой подход - норм

2023-07-30 20:28 UTC, s-shpak commented on internal/app/app.go
> +	Config *config.ServerConfig
Не вижу смысла делать это поле экспортируемым: другие компоненты не должны к нему обращаться

2023-07-30 20:28 UTC, s-shpak commented on internal/app/app.go
> +		hash, err := bcrypt.GenerateFromPassword([]byte(userReq.Password), 7) //TODO: check sha512, cryptoready
В принципе, можно исползовать и `bcrypt`, только лучше вынести парамметр в отдельную константу (потому что в дальнейшем он может быть и конфигурируемым)

2023-07-30 20:28 UTC, s-shpak commented on internal/app/app.go
> +	} else {
Лучше разнести на две функции

2023-07-30 20:28 UTC, s-shpak commented on internal/app/app.go
> +	c.SetCookie(auth.CookieName, jwt, 3600*24*30, "", "", false, true)
Я бы посоветовал все парамметры, которые могут быть конфигурируемыми потенциально (`maxAge`, например) выносить в отдельный параметр

2023-07-30 20:28 UTC, s-shpak commented on internal/middleware/logger/logger.go
> +		return nil, err
Ошибки из сторонних библиотек стоит оборачивать

2023-07-30 20:28 UTC, s-shpak commented on internal/middleware/logger/logger.go
> +	logger, err := zap.NewDevelopment()
А зачем создавать ноый логгер? Логгер лучше создавать в самом начале приложения, а потом прокидывать везде

2023-07-30 20:28 UTC, s-shpak commented on internal/app/router.go
> +		log.Fatal(err)
Не нао выходить из приложения в глубине кода

2023-07-30 20:28 UTC, s-shpak commented on internal/app/router.go
> +	r.Use(compress.Compress())
Кажется, что не все ответы следует сжимать

2023-07-30 20:28 UTC, s-shpak commented on internal/middleware/auth/auth.go
> +const UserIDKey = "userID"
Ключи контекста лучше объялять через йоту: https://stackoverflow.com/questions/40891345/fix-should-not-use-basic-type-string-as-key-in-context-withvalue-golint

2023-07-30 20:28 UTC, s-shpak commented on internal/app/app.go
> +		if err := req.Body.Close(); err != nil {
Тело запроса необязательно закрывать. Тем более необязательно отправлять `Internal Error` клиенту, еслипри закрытии возникла ошибка

https://stackoverflow.com/questions/42525499/where-to-put-defer-req-body-close

2023-07-30 20:28 UTC, s-shpak commented on internal/app/app.go
> +	userID := c.GetUint64(auth.UserIDKey)
А что если в контексте нет ID пользователя? Может стоит отправить ошибку раньше?

2023-07-30 20:28 UTC, s-shpak commented on internal/app/app.go
> +		} else {
Постарайся не добавлять `else` там, где он не нужен - здесь, к примеру

2023-07-30 20:28 UTC, s-shpak commented on internal/app/app.go
> +			log.Printf("unknown error: %v", err)
Стоит пользоваться едиым логером

2023-07-30 20:28 UTC, s-shpak commented on internal/app/app.go
> +	u, err := a.store.GetUser(&models.User{ID: userID})
Т.к. для выполнения этого действия необходимо совершить несколько запросов к БД, то эти запросы должны быть внутри транзакции. Но, конечно, контроллер о транзакциях не должен знать ничего

2023-07-30 20:28 UTC, s-shpak commented on internal/adapters/accrual/accrual_test.go
Здесь либо стоит добавить тесты, либо удалить этот файл

2023-07-30 20:28 UTC, s-shpak commented on internal/adapters/accrual/accrual.go
> +		return nil, NewServiceBisyError(time.Duration(cooldown)*time.Second, preparedRPM, err)
Как мы и обсуждали, значение cooldown надо правильно обрабатывать и использовать

2023-07-30 20:28 UTC, s-shpak commented on internal/adapters/accrual/accrual.go
> +// retryable (hashicorp) 5xx
!

2023-07-30 20:28 UTC, s-shpak commented on internal/adapters/accrual/accrual.go
> +		r := regexp.MustCompile(`(\d+)`)
`MustCompile` (вообще функции начинающиеся с `Must`) нужны для объявления переменных на уровне пакета, вне фукнций при старте приложения (они паникуют в случае ошибки). Так что этот регэксп можно скомпилировать заранее, а не при каждом вызове этой функции

2023-08-01 08:58 UTC, rawen554 commented on internal/adapters/store/store.go
> +func NewPostgresStore(ctx context.Context, dsn string, logLevel logger.LogLevel) (Store, error) {
Исключительно для удобства навигации по коду.
Буду возвращать свою структуру. Перенесу интерфейс в app, все таки он должен использовать этот интерфейс.

2023-08-03 21:57 UTC, s-shpak commented on .golangci-lint.yml
Все еще репортит

2023-08-03 22:01 UTC, s-shpak commented on cmd/gophermart/main.go
> +		logger.Panic(err)
Не наддо паниковать: лучше используй Fatal

2023-08-03 22:01 UTC, s-shpak commented on cmd/gophermart/main.go
> +	storage, err := store.NewPostgresStore(ctx, config.DatabaseURI, logger.LogLevel(config.LogLevel))
Пока инициализация дочерних логгеров не сделана: см. https://pkg.go.dev/go.uber.org/zap#SugaredLogger.With

2023-08-03 22:02 UTC, s-shpak commented on internal/adapters/store/store.go
> +func NewPostgresStore(ctx context.Context, dsn string, logLevel logger.LogLevel) (Store, error) {
Пока все еще возвращается интерфейс

2023-08-03 22:05 UTC, s-shpak commented on internal/adapters/accrual/accrual.go
> +		return nil, NewServiceBisyError(time.Duration(cooldown)*time.Second, preparedRPM, err)
Кажется, что пока не сделано

2023-08-03 22:06 UTC, s-shpak requested changes
Дай мне, пожалуйста, права на запись в репо, чтобы я мог резолвить комменты

И, пожалуйста, доделай использоавние cooldown при `Too Many Requests`, это ультра важно

2023-08-05 15:00 UTC, rawen554 commented on cmd/gophermart/main.go
> +		logger.Panic(err)
Линтер рекомендует паниковать, тк. при фатале не выполнится defer на 29 строке.

2023-08-05 17:42 UTC, s-shpak commented on cmd/gophermart/main.go
> +		logger.Panic(err)
Это можно решить без паники: вынеси все в отдельную функцию `run`, которая будет вызываться из `main` и вызывай `Fatal` в main

2023-08-06 11:06 UTC, s-shpak approved these changes

2023-08-06 11:53 UTC, merged